# הגדרות מדיה - איפה נשמרות התמונות שאתה מעלה
media:
  input: assets/images      # התיקייה בגיטהאב שאליה יעלו התמונות
  output: /assets/images    # הנתיב שהאתר ישתמש בו כדי להציג את התמונה

# הגדרות התוכן
content:
  - name: posts             # מזהה פנימי למערכת
    label: פוסטים (Blog)    # מה שכתוב בתפריט הצד
    type: collection        # סוג: אוסף של פריטים
    path: _posts            # התיקייה שבה ג'קיל מחפש את הפוסטים
    
    # תבנית שם הקובץ - קריטי לג'קיל! חייב להתחיל בתאריך
    filename: "{year}-{month}-{day}-{slug}.md"
    
    # פורמט הקובץ - ג'קיל עובד עם Frontmatter (ההגדרות בראש הקובץ)
    format: frontmatter 
    
    # מה רואים ברשימה הראשית לפני שנכנסים לערוך
    view:
      fields: [title, date, image]
      
    # השדות שיהיו בטופס העריכה
    fields:
      # שדה מוסתר שמגדיר לג'קיל שזהו "פוסט"
      - name: layout
        type: string
        default: post
        hidden: true

      - name: title
        label: כותרת הפוסט
        type: string
        required: true

      - name: date
        label: תאריך פרסום
        type: date
        required: true
        
      - name: image
        label: תמונה ראשית
        type: image
        
      - name: description
        label: תקציר (אופציונלי)
        type: text
        
      - name: body
        label: תוכן הפוסט
        type: rich-text
        required: true